apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "analytics.name" . }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
