apiVersion: v1
kind: Service
metadata:
  name: django-hello-service
spec:
  type: NodePort
  selector:
    app: django-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
