namespace: network-monitoring
dashboard:
  replicaCount: 1
  image:
    repository: dashboard
    tag: v3

analytics:
  replicaCount: 1
  image:
    repository: analytics
    tag: v2

simulator:
  replicaCount: 3
  image:
    repository: simulator
    tag: v1

redis:
  enabled: true

ingress:
  enabled: true
  host: network-monitoring.local
